### ISSUE TITLE
Is it possible to cache clients, too?

### ISSUE THREAD

**Issue by hirakujira** [overtrue/laravel-passport-cache-token#1]
Thanks for providing this useful package!

I am wondering whether it's possible to provide oauth_client caches, too?
Like this: https://learnku.com/articles/34272

Thanks!

**Comment by overtrue** [comment]
Hello, 这个缓存的使用场景是什么？

**Comment by hirakujira** [comment]
謝謝回覆，不過我忘記當時為何我問這個問題了 😅
