### ISSUE TITLE
Support for Passport 11

### ISSUE THREAD

**Issue by DreadfulCode** [overtrue/laravel-passport-cache-token#18]
Hi! While trying out a Laravel upgrade it was noticed that this package is not supported with Laravel 9/Passport 11. Works just fine in Lararvel 8/ Passport 10.

Are there any plans to support this version? Or is this now included in the Passport v11/L9 core and I am missing a setup step?

**Comment by mbardelmeijer** [comment]
Would be interested in this as well!

**Comment by overtrue** [comment]
@DreadfulCode @mbardelmeijer Hi, this package was created because of this issue: https://github.com/laravel/passport/issues/382 . But the new version of passport has officially solved this issue at: https://github.com/laravel/passport/pull/1447, so I think we can stop needing this package.

**Comment by binaryfire** [comment]
@overtrue Hi! Even though this has been improved in the new version of Passport, there are still 2 queries to the `oauth_access_tokens` table (see below). My understanding is that with your package, there would only be a single query to `oauth_clients` after the token has been cached? Which is still a significant improvement, especially when there are lots of concurrent users. Or have I misunderstood?


Before:

```
select * from `oauth_access_tokens` where `id` = ? limit 1
select * from `oauth_access_tokens` where `id` = ? limit 1
select * from `oauth_clients` where `id` = ? limit 1
select * from `oauth_access_tokens` where `id` = ? limit 1
select * from `oauth_clients` where `id` = ? limit 1
```
Passport 11:

```
select * from `oauth_access_tokens` where `id` = ? limit 1
select * from `oauth_clients` where `id` = ? limit 1
select * from `oauth_access_tokens` where `id` = ? limit 1
```

After token has been cached with your package:

```
select * from `oauth_clients` where `id` = ? limit 1
```

**Comment by overtrue** [comment]
@binaryfire Indeed, I haven't verified its optimization specifically, and as you say, it reduces queries, but not to the point of only querying the database once, so you can still choose to use this package as a cache.

**Comment by waney** [comment]
> 

Still need.
[laravel-passport-cache-client]
