### ISSUE TITLE
Update to Laravel 8 and Passport 10

### ISSUE THREAD

**Issue by rgr** [overtrue/laravel-passport-cache-token#3]
Hi,

would it be big work to make it available to Laravel 8 and Passport 10 ?

Thanks !

**Comment by overtrue** [comment]
I've submitted a change, if you have time to help test it, thanks:

```bash
$ composer require overtrue/laravel-passport-cache-token:dev-master -vvv
```

**Comment by rgr** [comment]
Thanks ! So I tried it, no errors but I still have 2 oauth_clients calls and 3 oauth_access_tokens calls in my route call.

Is there any way of checking if the caching is applied? (I ran a dump-autoload again after install just in case)

**Comment by overtrue** [comment]
Did you registered the provider? 

```php
Overtrue\LaravelPassportCacheToken\CacheTokenServiceProvider::class,
```

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-passport-cache-token/commit/fa82bf51d0123f1c7ff02a055d849913528cf4f6

**Comment by overtrue** [comment]
I forgot to auto-register for this package and have made it up.

**Comment by rgr** [comment]
yep thanks ! Because in the doc it said you do't have to do anything...so I didn't ;)

It works the oauth_access_tokens, not yet for the oauth_client !

Great package anyway :)

**Comment by overtrue** [comment]
@LearningRaph Thank you. 2.0.0 has been released: https://github.com/overtrue/laravel-passport-cache-token/releases/tag/2.0.0

**Comment by rgr** [comment]
I removed and required again and looks like it's working fine !

**Comment by overtrue** [comment]
@LearningRaph 😆 OK.
