### ISSUE TITLE
duplicated  oauth_clients

### ISSUE THREAD

**Issue by baselrabia** [overtrue/laravel-passport-cache-token#6]
Still have this query duplicated 

`select * from 'oauth_clients' where 'id' = '1' limit 1`

 Using 
        "laravel/passport": "9.3",
        "laravel/framework": "^7.29",

**Comment by overtrue** [comment]
sorry, it just caches the oauth_token.

**Comment by itailulu** [comment]
Would it make sense to add this functionality to this package too or to a new package?

**Comment by mbardelmeijer** [comment]
Have the same question here. Would be nice that this package handles oauth_clients caching as well.

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-passport-cache-client @itailulu @mbardelmeijer Welcome to try.
