### ISSUE TITLE
This cache store does not support tagging.

### ISSUE THREAD

**Issue by r0hitch0pra** [overtrue/laravel-passport-cache-token#7]
Version 2.2 is giving this error when trying to use personal access tokens when using the file cache storage. How do we get around this? Using Array is useless for caching and I dont want to install memcached

 "message": "This cache store does not support tagging."

**Comment by overtrue** [comment]
I will fix it.

**Comment by overtrue** [comment]
@r0hitch0pra please take a try with master branch or update your vendor code follow the commit [c2a8d3a44ca20cb4ebe17d87dd996e9c45c33ed1](https://github.com/overtrue/laravel-passport-cache-token/commit/c2a8d3a44ca20cb4ebe17d87dd996e9c45c33ed1).
