### ISSUE TITLE
smartins/passport-multiauth包的相关问题

### ISSUE THREAD

**Issue by renkx** [overtrue/laravel-passport-cache-token#9]
smartins/passport-multiauth最高版本为v7.0.0，requires指定的passport版本为laravel/passport: ^8.0。

overtrue/laravel-passport-cache-token的requires指定的passport版本为laravel/passport: ^9.2|^10.0

只要使用了passport-multiauth，就不能用laravel-passport-cache-token。

非常纠结。。。。

**Comment by overtrue** [comment]
这就没办法了
